### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mikedstark** [mfgravesjr/finished-projects#1]
Hello, do you have a particular license for this code? Are we free to use it in our own projects? Thank you and have a nice day!

**Comment by mfgravesjr** [comment]
Which project did you want to use? Is it for school or business?

**Comment by mikedstark** [comment]
The Sudoku generator. I would eventually use it for business, with your
permission of course. If not, I will use my own slower method. I was very
impressed with your YouTube video and how fast you can generate a million
puzzles.

**Comment by mfgravesjr** [comment]
You may use the code. But would you like me to help code for you in your
business endeavor? I'm still in the middle of programming a solver. I have
about 20 strategies coded already.

**Comment by mikedstark** [comment]
Thank you! I really appreciate the offer, but I don't have a lot of free time at the moment. I can't commit to anything serious at the moment, but maybe we can collaborate in the future!
